### ISSUE TITLE
Juman error

### ISSUE THREAD

**Issue by keikmin** [neilctwu/YouyakuMan#7]
I'm trying to use youyakuman with colaboratory, and the command is this.
`!python youyakuman.py -txt_file testjp.txt -lang jp -n 3 --super_long`

I tried this with Juman++ v2.0.0-rc2 and v2.0.0-rc3, but having the same error.
```
Traceback (most recent call last):
  File "youyakuman.py", line 41, in <module>
    lf = LangFactory(args.lang)
  File "/content/drive/My Drive/bert/YouyakuMan-master/src/LangFactory.py", line 29, in __init__
    self._toolchooser()
  File "/content/drive/My Drive/bert/YouyakuMan-master/src/LangFactory.py", line 33, in _toolchooser
    self.toolkit = JapaneseWorker()
  File "/content/drive/My Drive/bert/YouyakuMan-master/src/LangFactory.py", line 42, in __init__
    self.juman_tokenizer = JumanTokenizer()
  File "/content/drive/My Drive/bert/YouyakuMan-master/src/LangFactory.py", line 14, in __init__
    option=config['Juman']['option'])
  File "/usr/local/lib/python3.6/dist-packages/pyknp/juman/juman.py", line 47, in __init__
    raise Exception("Can't find JUMAN command: %s" % self.command)
Exception: Can't find JUMAN command: /Tools/jumanpp-2.0.0/bld/src/jumandic/RelWithDebInfo/jumanpp_v2``
```
I also thought the error is coming from the way I built, but I don't know what's wrong with it.
```
!wget https://github.com/ku-nlp/jumanpp/releases/download/v2.0.0-rc3/jumanpp-2.0.0-rc3.tar.xz && \
tar xJvf jumanpp-2.0.0-rc3.tar.xz && \
rm jumanpp-2.0.0-rc3.tar.xz && \
cd jumanpp-2.0.0-rc3/ && \
mkdir bld && \
cd bld && \
cmake .. \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX=/usr/local && \
make && \
sudo make install
```

Does anyone know what is wrong with it?

Thanks.

**Comment by neilctwu** [comment]
Hi @keikmin ,
This is probably because of path to `jumanpp_v2` in your system. You can change ['Juman']['option'] in config.ini to executable jumanpp_v2.

**Comment by keikmin** [comment]
Thanks.

I still have to tweak something, but probably seems to be perfect solution.
